### ISSUE TITLE
Prepare advanced annotation

### ISSUE THREAD

**Issue by xtracko** [RECETOX/recetox-xMSannotator#3]
I've divided this issue into 4 subtasks which can be worked on independently:
- [ ] Scores - wrap the original function `get_chemscorev1.6.71` and mitigate its side effects
- [ ] Pathways loading - Load CSV file containing pathway mapping and return a tibble with `pathway` and `compound` columns. Provide a parameter to specify the mapping of columns from the CSV file to the tibble.
- [ ] Pathways computation - Rewrite the function 'multilevelannotationstep3' using tidyverse. The function will take the tibble of pathway_mapping as an parameter. Check the correctness of the two Fisher tests which struct me rather odd.
- [ ] Tests - Create a simple test similar to the tests in RECETOX/xMSannotator#5

**Comment by hechth** [comment]
See also #6

**Comment by hechth** [comment]
I think with finishing the October prototype we can close this issue and then continue working on actual problems in the individual steps.
