### ISSUE TITLE
Pin the dependencies and create a package/dockerfile

### ISSUE THREAD

**Issue by martenson** [RECETOX/recetox-xMSannotator#4]
so we know exactly how to reproduce

https://github.com/RECETOX/xMSannotator/blob/master/Dockerfile#L10

**Comment by hechth** [comment]
@martenson All dependencies (for this version and the original xMSannotator) can be installed via conda - does this mean we can close this issue?

**Comment by martenson** [comment]
Yeah, it was basically superseded by https://github.com/RECETOX/recetox-xMSannotator/issues/4 I think.
