### ISSUE TITLE
main: Add QC compounds to HMDB database used for annotation

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-xMSannotator#43]
The version of HMDB doesn't contain the standards used in the QC samples that are used as testing data.

**Comment by ElliottJP** [comment]
Alongside adding to the database to test annotations, the other option is also to use these standards are input for the hybrid ROI apLCMS - so can then test that too. 
Also, in hyrbid - I assume it annotes known features then only unknown featurs are sent to xmsAnnotator for putative annotation?

**Comment by hechth** [comment]
@ElliottJP as I see it, apLCMS only adds the features detected via the known feature list to the output feature table and the new list of known compounds. It is possible to afterwards remove them from the feature table and not annotate them using xMSannotator, but the default approach would be to still do the annotation via xMSannotator.

I think the most reasonable thing to do would be to either (i) as you said, pull out those features and just annotate them using the known feature table or (ii) cross-check the annotations afterwards if they match the content in the known feature table.

**Comment by maximskorik** [comment]
The compound table (with QC compounds) is now on [GitLab](https://gitlab.ics.muni.cz/umsa/umsa-files/-/blob/master/testdata/recetox-xMSannotator/compounds.rds). A short description of the table is in comments to the [PR](https://gitlab.ics.muni.cz/umsa/umsa-files/-/merge_requests/2).
