### ISSUE TITLE
support apache parquet as input format

### ISSUE THREAD

**Issue by martenson** [RECETOX/recetox-xMSannotator#5]
corresponds to https://github.com/RECETOX/recetox-aplcms/issues/13

**Comment by hechth** [comment]
I think this should already be possible: https://github.com/RECETOX/recetox-xMSannotator/blob/088076f799cb4baa8a9690971a42d14a3384f661/xmsannotator/R/utils.R#L73-L78

@xtracko Can you confirm that? Then we can close the issue :)

**Comment by hechth** [comment]
@xtracko @martenson Maybe this could also be moved to the xMSannotator Galaxy wrapper same as aplcms? In order to keep the library lean and clean.

**Comment by martenson** [comment]
I am not sure, maybe we should discuss this in detail. If there is any heavy lifting involved it might make more sense as part of the binary.

**Comment by martenson** [comment]
I'd say this is fine for now. We switched to our own package and it makes sense that it supports our input format.
