### ISSUE TITLE
master: reformat all documents to have uniform layout

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-xMSannotator#51]
We should define a common formatting style for autoformatting to avoid having PRs in which a file is depicted as completely changed simply due to reformatting. This is also the case for different IDE's etc., which use autoformatting - it would be great to have one style according to which we format everything.

This can then also be transferred to all R based projects. And example for a style guide is given [here](https://stackoverflow.com/questions/15703553/auto-format-r-code-in-rstudio).

**Comment by hechth** [comment]
@xtrojak @martenson @maximskorik @xtracko I'd recommend from now on to use this package for formatting: https://styler.r-lib.org/reference/style_pkg.html

It actually has a plugin as R studio addin, so it can be used from the UI, but it can also be used from R directly via the API. This allows everyone who develops to use the same style guide, which is also the official tidyverse style guide.

This should resolve at least the larger problems, some fine-tuning can be individual, doesn't have to be 100% the same - but the auto-formatting should at least be.

The package is also in conda, so no need to change anything. I think this would be a good starting point to unify the R code in our packages.

**Comment by martenson** [comment]
I don't have any style preference but I'd suggest to include it in the CI, otherwise it is hard to converge on it.

**Comment by hechth** [comment]
@martenson That is a good point - we can also add this to the CI to automatically format the code.

That would even more speak for this solution as it is implemented as an R package, so it is easy to run.

**Comment by hechth** [comment]
@martenson We can also use the [knitr](https://www.rdocumentation.org/packages/knitr/versions/1.36/topics/knit_rd) package to compile the documentation generated via roxygen into a static HTML page.
