### ISSUE TITLE
master: update to fixed R version (>=4.0) and remove old dependencies

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-xMSannotator#57]
@martenson @ElliottJP Since `dataCompareR` as well as `patrick` due to being hosted on conda-forge have the latent R dependency problem (see #47 and #56 ), I'm debating removing old dependencies and not immediately required functionality (such as [Chemspider Annotation](https://github.com/RECETOX/recetox-xMSannotator/blob/master/R/ChemSpider.annotation.R)) to reduce the dependencies (especially the SSOAP package seems problematic).

**Comment by ElliottJP** [comment]
Fine by me - it will have little implications since other functionality is rarely used (internal & from what I'm aware by external users).
