### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-xMSannotator#8]
Individual parts of #1 & #4 

Original Tool:
~~- [ ] Get r-ssoap into conda in version 0.9~~ (seems not needed now)
- [x] environment-dev.yaml
- [ ] environment-build.yaml
- [ ] environment.yaml
- [ ] meta.yaml
- [ ] Draft release
- [ ] Publish to Bioconda

Our Tool:
- [x] environment-dev.yaml
- [x] environment-build.yaml
- [ ] environment.yaml
- [x] meta.yaml
- [ ] Draft release
- [ ] Publish to Bioconda

**Comment by martenson** [comment]
wip at https://github.com/bioconda/bioconda-recipes/pull/27848

**Comment by martenson** [comment]
I made a new [release](https://github.com/RECETOX/recetox-xMSannotator/releases/tag/v0.9.0) of this project with restarted versioning(0.9.0), since we're branching from upstream & updated it in the bioconda PR.

**Comment by martenson** [comment]
v0.9.0 published https://anaconda.org/bioconda/r-recetox-xmsannotator
